### ISSUE TITLE
Support Sitecore 8.2

### ISSUE THREAD

**Issue by dsolovay** [dsolovay/Sitecore-Instance-Manager#36]

**Comment by dsolovay** [comment]
Current code fails with this error:

```
Server Error in '/' Application.

Could not resolve type name: Sitecore.ContentSearch.SolrProvider.Pipelines.Loader.InitializeSolrProvider, Sitecore.ContentSearch.SolrProvider (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: Could not resolve type name: Sitecore.ContentSearch.SolrProvider.Pipelines.Loader.InitializeSolrProvider, Sitecore.ContentSearch.SolrProvider (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[Exception: Could not resolve type name: Sitecore.ContentSearch.SolrProvider.Pipelines.Loader.InitializeSolrProvider, Sitecore.ContentSearch.SolrProvider (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).]
   Sitecore.Diagnostics.Error.Raise(String error, String method) +137
   Sitecore.Configuration.DefaultFactory.CreateType(XmlNode configNode, String[] parameters, Boolean assert) +308
   Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +71
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +165
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, Boolean assert) +68
   Sitecore.Pipelines.CorePipelineFactory.GetObjectFromType(XmlNode processorNode) +91
   Sitecore.Pipelines.CorePipelineFactory.GetProcessorObject(XmlNode processorNode) +138
   Sitecore.Pipelines.CoreProcessor.GetMethod(Object[] parameters) +141
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +470
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
   Sitecore.Nexus.Web.HttpModule.Application_Start() +259
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +680
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +618
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Could not resolve type name: Sitecore.ContentSearch.SolrProvider.Pipelines.Loader.InitializeSolrProvider, Sitecore.ContentSearch.SolrProvider (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +716
```

**Comment by dsolovay** [comment]
Downloading support package 2.0.0 changed the error to the following:

```
Server Error in '/' Application.

Could not load file or assembly 'Autofac, Version=2.5.2.830, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'Autofac, Version=2.5.2.830, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'Autofac, Version=2.5.2.830, Culture=neutral, PublicKeyToken=17863af14b0044da' could not be loaded.


WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Stack Trace: 


[FileNotFoundException: Could not load file or assembly 'Autofac, Version=2.5.2.830, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.]
   Sitecore.ContentSearch.SolrProvider.AutoFacIntegration.AutoFacInitializeSolrProvider.Process(PipelineArgs args) +0
   (Object , Object[] ) +71
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
   Sitecore.Nexus.Web.HttpModule.Application_Start() +259
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +680
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +618
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Could not load file or assembly 'Autofac, Version=2.5.2.830, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +716

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0
```

**Comment by dsolovay** [comment]
Per [Release Notes](https://dev.sitecore.net/Downloads/Sitecore%20Experience%20Platform/82/Sitecore%20Experience%20Platform%2082%20Initial%20Release/Release%20Notes),

> Search and indexing no longer requires a third-party DI container to enable Solr and there is no need for a Solr support package.​

**Comment by dsolovay** [comment]
- [x] Add logic to skip enabling IOC config files (include with 2.0.0 package).  
- [x] Need to add logic to leave "luenceDefaultConfiguration" in place.  
- [x] Need to determine whether settings in Sitecore.ContentSearch.config (ContentSearch.DefaultIndexType, and ContentSearch.DefaultIndexConfigurationPath) can be left pointing to Luence.
- [x] Fix error: "An index with the name "sitecore_analytics_index" have already been added."
- [x] Fix Solr error with sitecore_core_index. See  next comment.
- [x] Ensure Term Support is enabled. See Sitecore [documentation](https://doc.sitecore.net/sitecore_experience_platform/80/setting_up__maintaining/search_and_indexing/walkthrough_setting_up_solr#_Toc399318998).  Moved to #38.
- [x] Verify 8.2 works.
- [x] Verify 8.1 works.
- [x] Code cleanup.
- [x] Update README.md
- [x] Pull request.
- [ ] Profit! :shipit:

**Comment by dsolovay** [comment]
**UPDATE**:  This looks like it was caused by the number of test indexes I had (over 50 from developing this feature). I removed them using [this script](http://stackoverflow.com/a/39937503/402949) and the issue went away.

---

All indexes except sitecore_core_index rebuild successfully. The latter produces this error:

Indexing Manager
An error occurred while rebuilding the search index.

Job started: Index_Update_IndexName=sitecore_core_index|#Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> SolrNet.Exceptions.SolrConnectionException: <?xml version="1.0" encoding="UTF-8"?>

**Comment by dsolovay** [comment]
**Update**: See above.  Runs clean now that I've reduced the number of indexes I have.

---

This error occurred for the first time:

```
System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
   at System.Net.HttpWebRequest.GetResponse()
   at SIM.WebRequestHelper.RequestAndGetResponse(Uri uri, Nullable`1 timeout, Nullable`1 readWriteTimeout, String cookies) in D:\projects\Sitecore-Instance-Manager\src\SIM.Base\WebRequestHelper.cs:line 237
```

**Comment by dsolovay** [comment]
Had issue with 1.0.0 manifest not loading, fixed by changing Copy To Output Directory to Copy Always.
![image](https://cloud.githubusercontent.com/assets/689532/19222109/fc5ea560-8e1e-11e6-9876-333702c659a7.png)

**Comment by dsolovay** [comment]
Now having issue with 1.0.0 not finding this class: 

```
Could not resolve type name: Sitecore.ContentSearch.SolrProvider.Pipelines.Loader.InitializeSolrProvider, Sitecore.ContentSearch.SolrProvider (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).
```

Development is fun! :smile_cat: 

**Update**: This was a testing error. I test the 8.1  manifest (1.0.0 160504) against an 8.2 install. D'oh. :frowning_face:

**Comment by dsolovay** [comment]
Merged into main repo.
